export const actionTypes = {
  GET_LOG: "GET_LOG",
  ADD_LOG: "ADD_LOG",
  EDIT_LOG: "EDIT_LOG",
  GO_BACK: "GO_BACK",
  GET_LOGS: "GET_LOGS",
  DELETE_LOG: "DELETE_LOG",
  CLEAR_CURRENT_PROFILE: "CLEAR_CURRENT_PROFILE",
  GET_ERRORS: "GET_ERRORS",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SEND_LOG: "SEND_LOG"
};
