export const actionTypes = {
  GET_LOG: "GET_LOG",
  ADD_LOG: "ADD_LOG",
  GET_LOGS: "GET_LOGS",
  DELETE_LOG: "DELETE_LOG",
  LOG_LOADING: "LOG_LOADING",
  PROFILE_LOADING: "PROFILE_LOADING",
  CLEAR_CURRENT_PROFILE: "CLEAR_CURRENT_PROFILE",
  GET_ERRORS: "GET_ERRORS",
  SET_CURRENT_USER: "SET_CURRENT_USER"
};
